services:

  hangman-words:
    image: hangman
    build: .
    command:
      - python
      - hangman/words.py
    ports:
      - "8001:8001"

  hangman-api:
    image: hangman
    build: .
    command:
      - python
      - hangman/api.py
    ports:
      - "8000:8000"

  hangman-cli:
    image: hangman
    build: .
    command:
      - python
      - hangman/cli.py
