services:

  hangman-api:
    image: hangman
    build: .
    command:
      - python
      - hangman/api.py
    ports:
      - "8000:8000"

  hangman-cli:
    image: hangman
    build: .
    command:
      - python
      - hangman/cli.py